apiVersion: v1
kind: Service
metadata:
  name: pipeline-health-dashboard
  labels:
    app.kubernetes.io/name: pipeline-health-dashboard
spec:
  selector:
    app.kubernetes.io/name: pipeline-health-dashboard
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
